using Microsoft.EntityFrameworkCore;

namespace backend.Data;

/// <summary>
/// 本地实体配置补充。
/// 数据库主键均为 GENERATED BY DEFAULT AS IDENTITY，但 scaffold 未识别出自增，
/// 因此这里显式声明由数据库 Identity 生成主键，应用层不再手工分配主键（修复并发下
/// MAX+1 分配主键导致的唯一约束冲突）。
/// 独立于 DB-First 生成文件，重新 scaffold 时不会覆盖此配置。
/// 注意：种子数据显式写入过主键，需把 Identity 序列同步到已写入的最大主键
/// （见 database/02_data.sql 末尾），否则自增值会与已有测试数据冲突。
/// </summary>
public partial class AppDbContext
{
    partial void OnModelCreatingPartial(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Models.SALE_ORDER>()
            .Property(x => x.SALE_ID)
            .ValueGeneratedOnAdd();

        modelBuilder.Entity<Models.SALE_ORDER_DETAIL>()
            .Property(x => x.SALE_DETAIL_ID)
            .ValueGeneratedOnAdd();

        modelBuilder.Entity<Models.INVENTORY>()
            .Property(x => x.INVENTORY_ID)
            .ValueGeneratedOnAdd();

        modelBuilder.Entity<Models.INVENTORY_RECORD>()
            .Property(x => x.RECORD_ID)
            .ValueGeneratedOnAdd();

        modelBuilder.Entity<Models.POINT_RECORD>()
            .Property(x => x.POINT_RECORD_ID)
            .ValueGeneratedOnAdd();

        // 以下两列在早期 scaffold 中显式声明为自增，新版 scaffold 未再生成，
        // 显式补上以免后续依赖运行时 identity 探测（scaffold 重生成时不会覆盖此文件）。
        modelBuilder.Entity<Models.SYS_USER>()
            .Property(x => x.USER_ID)
            .ValueGeneratedOnAdd();

        modelBuilder.Entity<Models.SYS_ROLE_MENU>()
            .Property(x => x.ROLE_MENU_ID)
            .ValueGeneratedOnAdd();

        // 采购模块（采购单主键自增，详见 database/02_data.sql 末尾的序列同步）
        modelBuilder.Entity<Models.PURCHASE_ORDER>()
            .Property(x => x.ORDER_ID)
            .ValueGeneratedOnAdd();

        modelBuilder.Entity<Models.PURCHASE_ORDER_DETAIL>()
            .Property(x => x.PURCHASE_DETAIL_ID)
            .ValueGeneratedOnAdd();
    }
}
