-- Oracle：为每日营业结转增加退款金额和净销售额。
-- 部署新版后端前执行一次；执行前请先在目标环境备份并核对表结构。
ALTER TABLE DAILY_SETTLEMENT ADD (
    REFUND_AMOUNT NUMBER(12,2) DEFAULT 0 NOT NULL,
    NET_SALES NUMBER(12,2) DEFAULT 0 NOT NULL
);

COMMENT ON COLUMN DAILY_SETTLEMENT.REFUND_AMOUNT IS '当日实际完成退款金额';
COMMENT ON COLUMN DAILY_SETTLEMENT.NET_SALES IS '当日净销售额（销售实收减退款金额）';

-- 为已有日结补算：退款按退货确认完成时间（UPDATE_TIME）归属自然日。
MERGE INTO DAILY_SETTLEMENT ds
USING (
    SELECT TRUNC(UPDATE_TIME) AS SETTLEMENT_DATE, SUM(REFUND_AMOUNT) AS REFUND_AMOUNT
    FROM RETURN_ORDER
    WHERE STATUS = '已完成' AND UPDATE_TIME IS NOT NULL
    GROUP BY TRUNC(UPDATE_TIME)
) r
ON (ds.SETTLEMENT_DATE = r.SETTLEMENT_DATE)
WHEN MATCHED THEN UPDATE SET ds.REFUND_AMOUNT = r.REFUND_AMOUNT;

UPDATE DAILY_SETTLEMENT
SET NET_SALES = NVL(TOTAL_SALES, 0) - NVL(REFUND_AMOUNT, 0);

COMMIT;
